trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  displayName: Create Vnet
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/create-vnet.ps1
    azurePowerShellVersion: latestVersion

- task: AzurePowerShell@5
  displayName: Create NSG
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/create-nsg.ps1
    azurePowerShellVersion: latestVersion

- task: AzurePowerShell@5
  displayName: Assign NSG To Subnet
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/assign-nsg-to-vnet.ps1
    azurePowerShellVersion: latestVersion

- task: AzurePowerShell@5
  displayName: Create VM
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/create-vm.ps1
    azurePowerShellVersion: latestVersion

- task: AzurePowerShell@5
  displayName: Create Linux Appservice
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/linux-appservice.ps1
    azurePowerShellVersion: latestVersion

- task: AzurePowerShell@5
  displayName: Create Storage Account
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/create-storage-account.ps1
    azurePowerShellVersion: latestVersion

- task: AzurePowerShell@5
  displayName: Create Windows Appservice
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/windows-appservice.ps1
    azurePowerShellVersion: latestVersion

- task: AzurePowerShell@5
  displayName: Create Backup
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/backup.ps1
    azurePowerShellVersion: latestVersion

- task: AzurePowerShell@5
  displayName: Delete Resources
  inputs:
    azureSubscription: build-agents
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)/delete-resources.ps1
    azurePowerShellVersion: latestVersion